### ISSUE TITLE
(setq solarized-use-variable-pitch nil) has no effect

### ISSUE THREAD

**Issue by martinklepsch** [bbatsov/solarized-emacs#129]
There is a very similar issue: #85. I have the following in my `init.el` to basically disable all proportional fonts and varying heights.

``` el
(setq solarized-use-variable-pitch nil)
(setq solarized-height-minus-1 1)
(setq solarized-height-plus-1 1)
(setq solarized-height-plus-2 1)
(setq solarized-height-plus-3 1)
(setq solarized-height-plus-4 1)
(load-theme 'solarized-dark t)
```

Still I get proportional (variable-pitch) fonts:

![proportional-headings.png](https://cloud.githubusercontent.com/assets/97496/4075229/b05f86f8-2eac-11e4-8fe7-f1cb517a16c6.png)

I also tried adding it to the very top of my `init.el` but that didn't make a difference.

I use a custom font like this `(set-default-font "M+ 1mn-15")`.

When I do `describe-face` on an org-mode heading I get the following:

```
Documentation:
Face used for level 1 headlines.

Defined in `org-faces.el'.

        Family: unspecified
       Foundry: unspecified
         Width: unspecified
        Height: 1
        Weight: unspecified
         Slant: unspecified
    Foreground: #cb4b16
    Background: unspecified
     Underline: unspecified
      Overline: unspecified
Strike-through: unspecified
           Box: unspecified
       Inverse: unspecified
       Stipple: unspecified
          Font: unspecified
       Fontset: unspecified
       Inherit: default
```

Any suggestions what could have gone wrong?
