### ISSUE TITLE
Selection background not working

### ISSUE THREAD

**Issue by Nebucatnetzer** [bbatsov/solarized-emacs#400]
I have a problem that the selection background doesn't get shown.
It only makes the text all black but nothing else.
That can make it sometimes very hard to see what I have selected.
![Screenshot from 2020-05-23 11-55-36](https://user-images.githubusercontent.com/2287221/82727710-735e5b80-9cec-11ea-9a65-a0aaa4366dee.png)

Below is my config for solarized-theme:
```
    (use-package solarized-theme
        :ensure t
        :config
        (setq solarized-use-variable-pitch nil)
        (setq solarized-scale-org-headlines nil)
        (setq x-underline-at-descent-line t)
        (setq solarized-high-contrast-mode-line t)
        (load-theme 'solarized-light t)))
```

**Comment by thomasf** [comment]
Make sure that you don't have multiple themes loaded.

It's supposed to look like this btw.


![image](https://user-images.githubusercontent.com/330847/82786661-4ed9bf00-9e65-11ea-8b4a-a5bf8e0d4195.png)

**Comment by thomasf** [comment]
`M-x describe-face RET region RET` 

```
          Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: #fdf6e3
DistantForeground: gtk_selection_fg_color
       Background: #586e75
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: t
          Inherit: unspecified
```

**Comment by Nebucatnetzer** [comment]
I've seen this problem on two machines.
One Windows 10 and one Ubuntu 20.04

This is the Windows face:
```
Face: region (sample) (customize this face)

Documentation:
Basic face for highlighting the region.

Defined in ‘faces.el’.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: #fdf6e3
DistantForeground: unspecified
       Background: #586e75
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: t
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: unspecified

[back]
```

The face on a Ubuntu Mate 20.04 machine where it is working.
```
Face: region (sample) (customize this face)

Documentation:
Basic face for highlighting the region.

Defined in ‘faces.el’.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: #fdf6e3
DistantForeground: unspecified
       Background: #586e75
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: unspecified
```

Once I'm back home I'll check the Ubuntu 20.04 machine as well.
I checked my custom.el on the Windows machine for any old theme configs but could find anything.
